services:
  app:
    image: python:3.9
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "5001:5000"
    command: bash -c "pip install -r requirements.txt && python app.py"

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8080:8080"
    environment:
      - CLEARML_API_ACCESS_KEY="OPDPAOBL8C8EFD6LHM0L72BSLI59FS"
      - CLEARML_API_SECRET_KEY="KvqSMf4BXpz9sAFmP6lzjE8a23lQuxSD-GkDrIXB0Vh2TjZ9Yuj2wan2_9whI4dgC8U"
